### ISSUE TITLE
[Error]  unable to fetch account id from script hash

### ISSUE THREAD

**Issue by timfaner** [YokaiSwap/yokaiswap-sdk#1]
Recently I tried to leverage sdk to build a price monitor, however encounter an Error.
I called `Fetcher.fetchPairData` and tried to get  **wckb**  and **yok** pair infomation and it returns:
```
> sdk.Fetcher.fetchPairData(yok,wckb,rpc)
Promise { <pending> }
> Uncaught:
Error: result from jsonRPC gw_get_account_id_by_script_hash is null or undefined. unable to fetch account id from script hash 0xad0e2846ca7b9ac10b99871d8619aaa5b287b5ffe30bd3883531d3ca12631bd9
    at Godwoker.jsonRPC (~/yokaiswap-sdk/node_modules/@polyjuice-provider/base/lib/util.js:448:33)
    at Godwoker.getAccountIdByScriptHash (~/yokaiswap-sdk/node_modules/@polyjuice-provider/base/lib/util.js:485:21)
    at Godwoker.allTypeEthAddressToAccountId (~/yokaiswap-sdk/node_modules/@polyjuice-provider/base/lib/util.js:786:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Godwoker.assembleRawL2Transaction (~/yokaiswap-sdk/node_modules/@polyjuice-provider/base/lib/util.js:612:20)
    at async buildProcess (~/yokaiswap-sdk/node_modules/@polyjuice-provider/base/lib/process.js:78:21)
    at async executeCallTransaction (~/yokaiswap-sdk/node_modules/@polyjuice-provider/base/lib/process.js:34:28)
    at async PolyjuiceJsonRpcProvider.send (~/yokaiswap-sdk/node_modules/@polyjuice-provider/ethers/lib/providers.js:89:28)
```

env is as follow:
```
process.env.REACT_APP_GW_CONTRACT_CODE_HASH = 
'0x636b89329db092883883ab5256e435ccabeee07b52091a78be22179636affce8'

process.env.REACT_APP_GW_ROLLUP_TYPE_HASH
'0x40d73f0d3c561fcaae330eabc030d8d96a9d0af36d0c5114883658a350cb9e3b'
```

token information as follow:
```
> wckb
Token {
  decimals: 8,
  symbol: 'WCKB',
  name: 'Wrapped CKB',
  chainId: 71394,
  address: '0xE934f463d026d97F6CE0A10215D0ac4224f0a930',
  projectLink: undefined
}

> yok
Token {
  decimals: 18,
  symbol: undefined,
  name: undefined,
  chainId: 71394,
  address: '0xb02c930C2825A960A50ba4Ab005e8264498b64a0',
  projectLink: undefined
}
```

I used  `polyjuice-provider/ethers` as provider and Init like :
```
polyjuiceConfig = {
    web3Url = "https://mainnet.godwoken.io/rpc"
}
rpc = new ether.PolyjuiceJsonRpcProvider(polyjuiceConfig,polyjuiceConfig.web3Url)

```

Everything seems fine but I got  an error ,I am totally confused, pls help 😂

**Comment by timfaner** [comment]
problem solved , add env as follow
```
process.env.REACT_APP_CHAIN_ID = 71394
process.env.REACT_APP_GW_CONTRACT_CREATOR_ACCOUNT_ID = "3"
process.env.REACT_APP_GW_CONTRACT_CODE_HASH = '0x636b89329db092883883ab5256e435ccabeee07b52091a78be22179636affce8'
process.env.REACT_APP_GW_ROLLUP_TYPE_HASH = '0x40d73f0d3c561fcaae330eabc030d8d96a9d0af36d0c5114883658a350cb9e3b'
```

**Comment by tianlitao** [comment]
> problem solved , add env as follow
> 
> ```
> process.env.REACT_APP_CHAIN_ID = 71394
> process.env.REACT_APP_GW_CONTRACT_CREATOR_ACCOUNT_ID = "3"
> process.env.REACT_APP_GW_CONTRACT_CODE_HASH = '0x636b89329db092883883ab5256e435ccabeee07b52091a78be22179636affce8'
> process.env.REACT_APP_GW_ROLLUP_TYPE_HASH = '0x40d73f0d3c561fcaae330eabc030d8d96a9d0af36d0c5114883658a350cb9e3b'
> ```

I have the same error as you, but setting env did not solve it, have you modified other places?
